### ISSUE TITLE
Making gender section inline

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Dateify#1]
First of all, set up the whole source code in your local system. Open the site on localhost:3000 on your system, start the backend and create your account so that you can go to the profile section of the site.  On the Edit profile interface, you can observe that the gender section containing male, female, and others is not in the same line. Your task is to make them horizontal.

**Comment by suju1811** [comment]
Heyyy @Arpitgupta1014  , I m a react enthusiastic and want to work on issue related to react.js so could you please assign this work to me

**Comment by Arpitgupta1014** [comment]
Sure

**Comment by Arpitgupta1014** [comment]
Nice work @Siddharth7899
