### ISSUE TITLE
Forgot Password 

### ISSUE THREAD

**Issue by jivteshsingh** [Arpitgupta1014/Dateify#3]
Hey, I would like to add the forgot password functionality in signin page. Can u please assign me this issue. I would like to work on it.
@Arpitgupta1014

**Comment by Arpitgupta1014** [comment]
Sure @jivteshsingh , It will be good for this project. I assigning it to you.

**Comment by jivteshsingh** [comment]
Hey, I have implemented the functionality and created a pull request.

**Comment by jivteshsingh** [comment]
@Arpitgupta1014
