### ISSUE TITLE
Delete Account 

### ISSUE THREAD

**Issue by jivteshsingh** [Arpitgupta1014/Dateify#5]
Hey, the delete account functionality is not working in the frontend. So I would like to work on it. Can u please assign me this issue.
@Arpitgupta1014

**Comment by Arpitgupta1014** [comment]
Hey @jivteshsingh ,I am assigning it to you. Look at the backend portion of forgot password too. It's backend portion is not working( btw Thankyou for your efforts on frontend part).

**Comment by jivteshsingh** [comment]
Hey, I have fixed the errors in frontend for forgot password. In backend there was not error and will be submitting the whole code tonight.
@Arpitgupta1014

**Comment by jivteshsingh** [comment]
Hey, I have implemented the functionality and created a pull request.
@Arpitgupta1014
